INSERT INTO category (name, slug) VALUES
('Web Development', 'web-development'),
('Mobile App Development', 'mobile-app-development'),
('Desktop App Development', 'desktop-app-development'),
('Game Development', 'game-development'),
('E-commerce Development', 'ecommerce-development'),
('CMS Development', 'cms-development'),
('DevOps & Cloud', 'devops-cloud'),
('QA & Testing', 'qa-testing'),
('Cybersecurity', 'cybersecurity'),
('Blockchain Development', 'blockchain-development'),
('API Development', 'api-development'),
('Scripting & Automation', 'scripting-automation'),
('AI Development', 'ai-development'),
('Machine Learning', 'machine-learning'),
('Deep Learning', 'deep-learning'),
('Natural Language Processing (NLP)', 'nlp'),
('Data Science', 'data-science'),
('Data Analysis', 'data-analysis'),
('Data Visualization', 'data-visualization'),
('Data Engineering', 'data-engineering'),
('UI/UX Design', 'ui-ux-design'),
('Graphic Design', 'graphic-design'),
('Logo Design & Branding', 'logo-design-branding'),
('Illustration', 'illustration'),
('Character Design', 'character-design'),
('Presentation Design', 'presentation-design'),
('Print Design', 'print-design'),
('3D Modeling & Animation', '3d-modeling-animation'),
('AR/VR Design', 'ar-vr-design'),
('Photography', 'photography'),
('Photo Editing', 'photo-editing'),
('Video Editing', 'video-editing'),
('Motion Graphics', 'motion-graphics'),
('Industrial Design', 'industrial-design'),
('Fashion Design', 'fashion-design'),
('Content Writing', 'content-writing'),
('Copywriting', 'copywriting'),
('Technical Writing', 'technical-writing'),
('Creative Writing', 'creative-writing'),
('Resume Writing', 'resume-writing'),
('Translation', 'translation'),
('Proofreading & Editing', 'proofreading-editing'),
('Transcription', 'transcription'),
('Digital Marketing', 'digital-marketing'),
('SEO (Search Engine Optimization)', 'seo'),
('SEM (Search Engine Marketing)', 'sem'),
('Social Media Marketing', 'social-media-marketing'),
('Email Marketing', 'email-marketing'),
('Content Marketing', 'content-marketing'),
('PPC Advertising', 'ppc-advertising'),
('Affiliate Marketing', 'affiliate-marketing'),
('Virtual Assistant', 'virtual-assistant'),
('Data Entry', 'data-entry'),
('Market Research', 'market-research'),
('Project Management', 'project-management'),
('Customer Support', 'customer-support'),
('IT Support', 'it-support'),
('Business Plan Writing', 'business-plan-writing'),
('Financial Modeling', 'financial-modeling'),
('Bookkeeping', 'bookkeeping'),
('Legal Consulting', 'legal-consulting'),
('Audio Production', 'audio-production'),
('Sound Design', 'sound-design'),
('Voice Over', 'voice-over'),
('Music Composition', 'music-composition');