INSERT INTO majors (id, name, alias) VALUES
('RPL', 'Rekayasa Perangkat Lunak', 'RPL'),
('TKJ', 'Teknik Komputer dan Jaringan', 'TKJ'),
('DKV', 'Desain Komunikasi Visual', 'DKV'),
('MM', 'Multimedia', 'MM'),
('BC', 'Broadcasting dan Perfilman', 'BC'),
('ANM', 'Animasi', 'ANM'),
('SIJA', 'Sistem Informasi, Jaringan, dan Aplikasi', 'SIJA'),
('AKL', 'Akuntansi dan Keuangan Lembaga', 'AKL'),
('OTKP', 'Otomatisasi dan Tata Kelola Perkantoran', 'OTKP'),
('BDP', 'Bisnis Daring dan Pemasaran', 'BDP'),
('BD', 'Bisnis Digital', 'BD'),
('PBS', 'Perbankan Syariah', 'PBS'),
('TKRO', 'Teknik Kendaraan Ringan Otomotif', 'TKR'),
('TBSM', 'Teknik dan Bisnis Sepeda Motor', 'TBSM'),
('TAB', 'Teknik Alat Berat', 'TAB'),
('TPM', 'Teknik Pemesinan', 'TPM'),
('TPL', 'Teknik Pengelasan', 'TPL'),
('TITL', 'Teknik Instalasi Tenaga Listrik', 'TITL'),
('TEI', 'Teknik Elektronika Industri', 'TEI'),
('TOI', 'Teknik Otomasi Industri', 'TOI'),
('TAV', 'Teknik Audio Video', 'TAV'),
('DPIB', 'Desain Pemodelan dan Informasi Bangunan', 'DPIB'),
('TPTU', 'Teknik Pendingin dan Tata Udara', 'TPTU'),
('KA', 'Kimia Analisis', 'KA'),
('KI', 'Kimia Industri', 'KI'),
('UPW', 'Usaha Perjalanan Wisata', 'UPW'),
('PH', 'Perhotelan', 'PH'),
('TBG', 'Tata Boga', 'TBG'),
('TSN', 'Tata Busana', 'TSN'),
('TKKR', 'Tata Kecantikan Kulit dan Rambut', 'TKKR'),
('DPK', 'Desain dan Produksi Kriya', 'DPK'),
('SP', 'Seni Pertunjukan', 'SP'),
('KEP', 'Asisten Keperawatan', 'KEP'),
('FARM', 'Farmasi', 'FARM'),
('TLM', 'Teknologi Laboratorium Medik', 'TLM'),
('DNT', 'Dental Asisten', 'DNT'),
('ATPH', 'Agribisnis Tanaman Pangan dan Hortikultura', 'ATPH'),
('APHP', 'Agribisnis Pengolahan Hasil Pertanian', 'APHP'),
('AT', 'Agribisnis Ternak', 'AT'),
('AP', 'Agribisnis Perikanan', 'AP'),
('NKPI', 'Nautika Kapal Penangkap Ikan', 'NKPI'),
('TKPI', 'Teknika Kapal Penangkap Ikan', 'TKPI'),
('NKN', 'Nautika Kapal Niaga', 'NKN'),
('TKN', 'Teknika Kapal Niaga', 'TKN');